/**
 * Report model -> one self-contained HTML document (NightVision light
 * letterhead), printed to PDF by pdf.ts.
 *
 * Security: every string from the model is target-derived or agent-written and
 * goes through esc(). The document also carries a CSP that forbids scripts and
 * any network fetch, so even a missed escape cannot run code or call out while
 * the browser renders it.
 */
import { NV_ICON_DATA_URI } from './brand.js';
import {
  SEVERITY_ORDER,
  type ProjectReport,
  type Report,
  type ReportFinding,
  type ScanReport,
  type Severity,
  type SeverityCounts,
} from './model.js';

export function esc(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

const SEVERITY_LABEL: Record<Severity, string> = {
  CRITICAL: 'Critical',
  HIGH: 'High',
  MEDIUM: 'Medium',
  LOW: 'Low',
  INFO: 'Info',
  UNSPECIFIED: 'Unspecified',
};

function formatDate(iso: string | null): string {
  if (!iso) return 'Unknown';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return esc(iso);
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric', timeZone: 'UTC' });
}

function formatDateTime(iso: string | null): string {
  if (!iso) return 'Unknown';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return esc(iso);
  return `${d.toLocaleString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', timeZone: 'UTC', hourCycle: 'h23',
  })} UTC`;
}

function formatDuration(seconds: number | null): string {
  if (seconds === null) return 'Unknown';
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  if (h > 0) return `${h}h ${m}m`;
  if (m > 0) return `${m}m ${s}s`;
  return `${s}s`;
}

function plural(n: number, one: string, many = `${one}s`): string {
  return `${n} ${n === 1 ? one : many}`;
}

/** Severities worth a tile: always the four core levels, Info only when it has findings. */
function visibleSeverities(counts: SeverityCounts): Severity[] {
  return SEVERITY_ORDER.filter((s) => ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].includes(s) || counts[s] > 0);
}

function chip(s: Severity): string {
  return `<span class="chip sev-${s.toLowerCase()}">${SEVERITY_LABEL[s]}</span>`;
}

/**
 * Scan explanations use a little Markdown (`code`, **bold**). Escape first,
 * then turn backtick spans into <code> and drop emphasis markers; nothing else
 * is interpreted.
 */
function explanationHtml(text: string): string {
  return esc(text.replace(/^\s*#{1,6}\s+[^\n]{0,40}\n+/, '').replace(/^#{1,6}\s+/gm, ''))
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/`([^`\n]{1,200})`/g, '<code>$1</code>');
}

/** Agent-written prose: blank-line paragraphs, "- " bullets. No markup is honored. */
function prose(text: string): string {
  const blocks = text.split(/\n\s*\n/).map((b) => b.trim()).filter(Boolean);
  return blocks.map((block) => {
    const lines = block.split('\n').map((l) => l.trim()).filter(Boolean);
    if (lines.every((l) => /^[-*•]\s+/.test(l))) {
      return `<ul class="bullets">${lines.map((l) => `<li>${esc(l.replace(/^[-*•]\s+/, ''))}</li>`).join('')}</ul>`;
    }
    return `<p>${esc(lines.join(' '))}</p>`;
  }).join('');
}

function severityBar(counts: SeverityCounts): string {
  const total = SEVERITY_ORDER.reduce((sum, s) => sum + counts[s], 0);
  if (total === 0) return '';
  const segments = SEVERITY_ORDER.filter((s) => counts[s] > 0)
    .map((s) => `<span class="seg sev-${s.toLowerCase()}" style="width:${((counts[s] / total) * 100).toFixed(2)}%"></span>`)
    .join('');
  return `<div class="bar" role="img" aria-label="Open findings by severity">${segments}</div>`;
}

function statTiles(counts: SeverityCounts): string {
  const tiles = visibleSeverities(counts).map((s) => `
      <div class="stat sev-edge-${s.toLowerCase()}">
        <div class="n">${counts[s]}</div>
        <div class="l">${SEVERITY_LABEL[s]}</div>
      </div>`).join('');
  return `<div class="stats">${tiles}</div>`;
}

function masthead(kicker: string, metaRight: string): string {
  return `
    <header class="masthead">
      <div class="brand"><img src="${NV_ICON_DATA_URI}" alt=""><span>NightVision</span></div>
      <div class="meta">${metaRight}</div>
    </header>
    <div class="kicker-row">${esc(kicker)}</div>`;
}

function closingLine(label: string): string {
  return `<p class="closing">${esc(label)} · Generated by NightVision · nightviz.ai</p>`;
}

function exclusionsNote(report: ScanReport): string {
  const parts: string[] = [];
  const ex = report.exclusions;
  if (ex.not_open) parts.push(`${plural(ex.not_open, 'finding')} marked resolved, false positive, or excluded`);
  if (ex.below_threshold) {
    parts.push(`${plural(ex.below_threshold, 'finding')} below the ${esc(SEVERITY_LABEL[normalizeMin(report.options.min_severity)])} severity threshold`);
  }
  if (!parts.length) return '';
  return `<p class="fine">Not included: ${parts.join('; ')}.</p>`;
}

function normalizeMin(min: string): Severity {
  const m = min.toUpperCase();
  return (m === 'INFO' ? 'INFO' : m) as Severity;
}

function coverageSection(report: ScanReport): string {
  const s = report.scan;
  const rows: Array<[string, string]> = [
    ['Target', `${esc(s.target_name)}${s.target_url ? ` <code>${esc(s.target_url)}</code>` : ''}`],
    ['Target type', esc(s.target_type ?? 'Unknown')],
    ['Scan window', `${formatDateTime(s.started_at)} to ${formatDateTime(s.ended_at)} (${formatDuration(s.duration_seconds)})`],
    ['Paths exercised', s.paths_tested === null ? 'Unknown' : String(s.paths_tested)],
    ['Engines', esc(s.engines.length ? s.engines.join(' + ') : 'Unknown')],
    ['API spec', s.spec_file ? `<code>${esc(s.spec_file)}</code>` : 'None (web crawl only)'],
    ['Linked to source code', s.source_linked_count
      ? `${plural(s.source_linked_count, 'finding')} ${s.source_linked_count === 1 ? 'maps' : 'map'} to a source file and line`
      : s.source_link_attempted
        ? 'No findings mapped to a specific handler'
        : s.spec_file
          ? 'Not linked (generate the report from the app source directory to map findings to code)'
          : 'Not applicable (web crawl without an API spec)'],
  ];
  if (s.excluded_url_patterns) rows.push(['Excluded URL patterns', String(s.excluded_url_patterns)]);
  return `
    <section class="sec">
      <h2><span class="tag">Scope</span>What was tested</h2>
      <table class="kv">${rows.map(([k, v]) => `<tr><th>${k}</th><td>${v}</td></tr>`).join('')}</table>
    </section>`;
}

function topIssuesSection(report: ScanReport): string {
  if (!report.top_findings.length) {
    return `
    <section class="sec">
      <h2><span class="tag">Priorities</span>Top issues</h2>
      <p class="body">No open findings at or above the ${esc(SEVERITY_LABEL[normalizeMin(report.options.min_severity)])} threshold.</p>
    </section>`;
  }
  const rows = report.top_findings.map((f) => `
      <tr>
        <td>${chip(f.severity)}</td>
        <td class="name">${esc(f.name)}</td>
        <td class="num">${f.affected_paths}</td>
        <td class="tax">${esc(f.taxonomy.map((t) => t.code).join(', ') || '')}</td>
      </tr>`).join('');
  return `
    <section class="sec">
      <h2><span class="tag">Priorities</span>Top issues</h2>
      <table class="grid">
        <thead><tr><th>Severity</th><th>Issue type</th><th class="num">Endpoints</th><th>Category</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </section>`;
}

function comparisonSection(report: ScanReport): string {
  const c = report.comparison;
  if (!c) return '';
  const list = (entries: typeof c.new_findings, empty: string) => entries.length
    ? `<table class="grid compact"><tbody>${entries.map((e) => `
        <tr><td>${chip(e.severity)}</td><td class="name">${esc(e.name)}</td>
        <td><code>${esc(e.method)} ${esc(e.path)}</code>${e.parameter ? ` <span class="muted">param</span> <code>${esc(e.parameter)}</code>` : ''}</td></tr>`).join('')}</tbody></table>`
    : `<p class="fine">${empty}</p>`;
  const more = (shown: number, total: number) => (total > shown ? `<p class="fine">Showing ${shown} of ${total}.</p>` : '');
  return `
    <section class="sec avoid-break">
      <h2><span class="tag">Change</span>Since the previous scan (${formatDate(c.baseline_started_at)})</h2>
      <div class="stats three">
        <div class="stat"><div class="n">${c.new_count}</div><div class="l">New</div></div>
        <div class="stat"><div class="n good">${c.fixed_count}</div><div class="l">Fixed</div></div>
        <div class="stat"><div class="n">${c.still_open_count}</div><div class="l">Still open</div></div>
      </div>
      <h3>New findings</h3>
      ${list(c.new_findings, 'None.')}${more(c.new_findings.length, c.new_count)}
      <h3>Fixed since the previous scan</h3>
      ${list(c.fixed_findings, 'None.')}${more(c.fixed_findings.length, c.fixed_count)}
      ${c.dismissed_count ? `<p class="fine">${plural(c.dismissed_count, 'finding')} from the previous scan ${c.dismissed_count === 1 ? 'is' : 'are'} still reported but now marked resolved or false positive, so ${c.dismissed_count === 1 ? 'it is' : 'they are'} not counted as fixed.</p>` : ''}
      <p class="fine">Baseline scan <code>${esc(c.baseline_scan_id)}</code>. Findings are matched by issue type, endpoint, and parameter.</p>
    </section>`;
}

function findingBlock(f: ReportFinding, includeEvidence: boolean): string {
  const tax = f.taxonomy.length
    ? `<p class="tax-line">${f.taxonomy.map((t) => `${esc(t.standard)} ${esc(t.code)}${t.name ? `: ${esc(t.name)}` : ''}`).join(' · ')}</p>`
    : '';
  const rows = f.occurrences.map((o) => `
        <tr>
          <td><code>${esc(o.method)}</code></td>
          <td class="ep"><code>${esc(o.path)}</code></td>
          <td>${o.parameter ? `<code>${esc(o.parameter)}</code>` : '<span class="muted">none</span>'}</td>
          <td>${o.source ? `<code>${esc(o.source.file)}${o.source.line !== null ? `:${o.source.line}` : ''}</code>` : '<span class="muted">not linked</span>'}</td>
        </tr>
        ${o.payload ? `<tr class="sub"><td></td><td colspan="3"><span class="muted">Payload</span> <code class="wrap">${esc(o.payload)}</code></td></tr>` : ''}
        ${includeEvidence && o.evidence ? `<tr class="sub"><td></td><td colspan="3"><span class="muted">Evidence</span> <code class="wrap">${esc(o.evidence)}</code></td></tr>` : ''}`).join('');
  const hiddenCount = f.occurrence_total - f.occurrences.length;
  const first = f.occurrences[0];
  return `
    <article class="finding sev-edge-${f.severity.toLowerCase()}">
      <div class="finding-head">
        ${chip(f.severity)}
        <h3>${esc(f.name)}</h3>
        <span class="count">${plural(f.affected_paths, 'endpoint')} · ${plural(f.occurrence_total, 'occurrence')}${f.engine ? ` · ${esc(f.engine)}` : ''}</span>
      </div>
      ${tax}
      ${f.explanation ? `<div class="explain"><div class="label">What NightVision observed</div><p>${explanationHtml(f.explanation)}</p></div>` : ''}
      ${f.remediation_note ? `<div class="fix"><div class="label">How to fix</div>${prose(f.remediation_note)}</div>` : ''}
      <table class="grid occ">
        <thead><tr><th>Method</th><th>Endpoint</th><th>Parameter</th><th>Source</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
      ${hiddenCount > 0 ? `<p class="fine">${plural(hiddenCount, 'more occurrence')} not shown. The full list is in NightVision.</p>` : ''}
      ${first ? `<div class="repro"><div class="label">Reproduce (first endpoint above; add your own session headers)</div><pre>${esc(first.curl)}</pre></div>` : ''}
    </article>`;
}

function scanBody(report: ScanReport): string {
  const s = report.scan;
  const metaRight = `<b>Report date</b> ${formatDate(report.generated_at)}<br><b>Scan</b> <code>${esc(s.scan_id)}</code>`;
  const lede = [
    s.target_url ? `<code class="on-dark">${esc(s.target_url)}</code>` : '',
    s.project_name ? `Project <b>${esc(s.project_name)}</b>` : '',
    `Scanned ${formatDate(s.started_at)}`,
  ].filter(Boolean).join(' · ');
  const summary = report.executive_summary
    ? `<section class="sec"><h2><span class="tag">Summary</span>What this means</h2><div class="body">${prose(report.executive_summary)}</div></section>`
    : '';
  const evidenceNote = report.options.include_evidence
    ? '<p class="fine">This report includes raw scan evidence. Handle it as sensitive.</p>'
    : '<p class="fine">Scan evidence is omitted and recognizable secrets in payloads, explanations, and commands are masked. Masking is best effort; review before sharing outside your organization.</p>';

  const appendix = report.findings.length
    ? `
    <section class="appendix">
      <h2 class="appendix-title"><span class="tag">Detail</span>Findings for developers</h2>
      <p class="body">Every open issue type, most severe first. Endpoints linked to source show the file and line of the handler that received the request.</p>
      ${report.findings.map((f) => findingBlock(f, report.options.include_evidence)).join('')}
      ${evidenceNote}
    </section>`
    : '';

  return `
    ${masthead('DAST security report', metaRight)}
    <div class="hero">
      <div class="kicker">${report.comparison ? 'Scan results and change since last scan' : 'Scan results'}</div>
      <h1>${esc(report.title)}</h1>
      <p>${lede}</p>
      <p class="hero-total"><b>${report.total_open}</b> open ${report.total_open === 1 ? 'finding' : 'findings'} across <b>${report.distinct_types}</b> issue ${report.distinct_types === 1 ? 'type' : 'types'}</p>
    </div>
    ${statTiles(report.counts)}
    ${severityBar(report.counts)}
    ${summary}
    ${topIssuesSection(report)}
    ${comparisonSection(report)}
    ${coverageSection(report)}
    ${exclusionsNote(report)}
    ${appendix}
    ${closingLine(`${s.target_name} · scan ${s.scan_id}`)}`;
}

function projectBody(report: ProjectReport): string {
  const metaRight = `<b>Report date</b> ${formatDate(report.generated_at)}<br><b>Project</b> ${esc(report.project_name)}`;
  const summary = report.executive_summary
    ? `<section class="sec"><h2><span class="tag">Summary</span>What this means</h2><div class="body">${prose(report.executive_summary)}</div></section>`
    : '';
  const sevCols = visibleSeverities(report.counts);
  const targetRows = report.targets.map((t) => `
      <tr>
        <td class="name">${esc(t.target_name)}${t.target_url ? `<br><code>${esc(t.target_url)}</code>` : ''}</td>
        <td>${formatDate(t.scanned_at)}</td>
        ${sevCols.map((s) => `<td class="num${t.counts[s] ? ` hot-${s.toLowerCase()}` : ''}">${t.counts[s]}</td>`).join('')}
      </tr>`).join('');
  const typeRows = report.top_types.map((t) => `
      <tr><td>${chip(t.severity)}</td><td class="name">${esc(t.name)}</td><td class="num">${t.targets}</td><td class="num">${t.affected_paths}</td></tr>`).join('');
  return `
    ${masthead('DAST security report', metaRight)}
    <div class="hero">
      <div class="kicker">Project roll-up</div>
      <h1>${esc(report.title)}</h1>
      <p>Latest completed scan of each target · ${plural(report.targets.length, 'target')}</p>
      <p class="hero-total"><b>${report.total_open}</b> open ${report.total_open === 1 ? 'finding' : 'findings'}</p>
    </div>
    ${statTiles(report.counts)}
    ${severityBar(report.counts)}
    ${summary}
    <section class="sec">
      <h2><span class="tag">Targets</span>Open findings by target</h2>
      ${report.targets.length ? `<table class="grid">
        <thead><tr><th>Target</th><th>Last scanned</th>${sevCols.map((s) => `<th class="num">${SEVERITY_LABEL[s]}</th>`).join('')}</tr></thead>
        <tbody>${targetRows}</tbody>
      </table>` : '<p class="body">No completed scans found in this project.</p>'}
    </section>
    ${report.top_types.length ? `
    <section class="sec">
      <h2><span class="tag">Priorities</span>Most widespread issue types</h2>
      <table class="grid">
        <thead><tr><th>Severity</th><th>Issue type</th><th class="num">Targets</th><th class="num">Endpoints</th></tr></thead>
        <tbody>${typeRows}</tbody>
      </table>
    </section>` : ''}
    <p class="fine">Counts are open findings only. For per-endpoint detail, source locations, and reproduction steps, generate a scan report for an individual target.</p>
    ${closingLine(`Project ${report.project_name}`)}`;
}

const STYLES = `
  @page { size: Letter; margin: 0.5in 0.55in 0.6in; }
  :root {
    --ink: #0B0F14; --body: #1B2229; --muted: #525B63; --line: #E4E8EC; --soft: #F4F6F8;
    --green: #7CFF41; --green-ink: #2F7D18;
    --critical: #C62F28; --high: #E0621B; --medium: #E8A317; --low: #3A78C9; --info: #7C8A98;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body { background: #fff; }
  body {
    font-family: "Helvetica Neue", Helvetica, Arial, "Segoe UI", "Liberation Sans", sans-serif;
    -webkit-font-smoothing: antialiased; color: var(--body);
    font-size: 9.6pt; line-height: 1.45;
    -webkit-print-color-adjust: exact; print-color-adjust: exact;
  }
  code, pre { font-family: "SF Mono", Menlo, Consolas, "Liberation Mono", monospace; }
  code { font-size: 8pt; background: var(--soft); padding: 0 3px; border-radius: 3px; color: var(--ink); word-break: break-all; }
  code.on-dark { background: #1B2531; color: #F5F7FA; }
  code.wrap { white-space: pre-wrap; }

  .masthead { display: flex; justify-content: space-between; align-items: flex-end; padding-bottom: 9px; border-bottom: 2px solid var(--ink); }
  .brand { display: flex; align-items: center; gap: 8px; font-weight: 800; font-size: 14pt; letter-spacing: -0.02em; color: var(--ink); }
  .brand img { height: 24px; width: 24px; }
  .meta { text-align: right; font-size: 7.8pt; color: var(--muted); line-height: 1.5; }
  .meta b { color: var(--ink); font-weight: 600; }
  .kicker-row { margin-top: 10px; font-size: 7.4pt; font-weight: 700; letter-spacing: 0.16em; text-transform: uppercase; color: var(--green-ink); }

  .hero { background: var(--ink); color: #F5F7FA; border-radius: 10px; padding: 14px 18px 13px; margin-top: 6px; }
  .hero .kicker { font-size: 7.4pt; font-weight: 700; letter-spacing: 0.14em; text-transform: uppercase; color: var(--green); }
  .hero h1 { color: #fff; margin: 4px 0 6px; font-size: 18pt; font-weight: 800; letter-spacing: -0.02em; line-height: 1.15; }
  .hero p { font-size: 9pt; color: #CFD6DE; }
  .hero p b { color: #fff; }
  .hero .hero-total { margin-top: 6px; font-size: 10pt; }
  .hero .hero-total b { color: var(--green); font-size: 12pt; }

  .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(0, 1fr)); gap: 8px; margin: 10px 0 8px; }
  .stat { background: var(--soft); border: 1px solid var(--line); border-radius: 8px; padding: 8px 11px; border-top-width: 3px; }
  .stat .n { font-size: 20pt; font-weight: 800; letter-spacing: -0.02em; line-height: 1.05; color: var(--ink); }
  .stat .n.good { color: var(--green-ink); }
  .stat .l { font-size: 8pt; margin-top: 3px; color: var(--muted); font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em; }
  .sev-edge-critical { border-top-color: var(--critical); } .sev-edge-high { border-top-color: var(--high); }
  .sev-edge-medium { border-top-color: var(--medium); } .sev-edge-low { border-top-color: var(--low); }
  .sev-edge-info, .sev-edge-unspecified { border-top-color: var(--info); }

  .bar { display: flex; height: 8px; border-radius: 4px; overflow: hidden; background: var(--soft); margin-bottom: 4px; }
  .seg.sev-critical { background: var(--critical); } .seg.sev-high { background: var(--high); }
  .seg.sev-medium { background: var(--medium); } .seg.sev-low { background: var(--low); }
  .seg.sev-info, .seg.sev-unspecified { background: var(--info); }

  .chip { display: inline-block; min-width: 54px; text-align: center; font-size: 7pt; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase; border-radius: 4px; padding: 2px 6px; color: #fff; white-space: nowrap; }
  .chip.sev-critical { background: var(--critical); } .chip.sev-high { background: var(--high); }
  .chip.sev-medium { background: var(--medium); color: var(--ink); } .chip.sev-low { background: var(--low); }
  .chip.sev-info, .chip.sev-unspecified { background: var(--info); }

  .sec { margin-top: 16px; }
  h2, h3 { break-after: avoid; }
  table.kv, .stats, .bar { break-inside: avoid; }
  h2 { font-size: 11pt; font-weight: 700; color: var(--ink); margin-bottom: 7px; letter-spacing: -0.005em; }
  h2 .tag { font-size: 7.2pt; font-weight: 700; color: var(--green-ink); text-transform: uppercase; letter-spacing: 0.08em; margin-right: 7px; }
  h3 { font-size: 9.4pt; font-weight: 700; color: var(--ink); margin: 10px 0 5px; }
  .body p { margin-bottom: 6px; }
  .body, .body p { color: var(--body); }
  ul.bullets { margin: 0 0 6px 16px; }
  ul.bullets li { margin-bottom: 3px; }
  .muted { color: var(--muted); font-size: 8pt; }
  .fine { font-size: 7.8pt; color: var(--muted); margin-top: 6px; }

  table { width: 100%; border-collapse: collapse; font-size: 8.6pt; }
  table.grid th, table.grid td { padding: 5px 8px; text-align: left; border-bottom: 1px solid var(--line); vertical-align: top; }
  table.grid thead th { background: var(--soft); font-size: 7.2pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; color: var(--muted); }
  table.grid td.name { font-weight: 600; color: var(--ink); }
  table.grid .num { text-align: right; white-space: nowrap; }
  table.grid td.tax { color: var(--muted); }
  table.compact td { padding: 3px 6px; }
  td.hot-critical { color: var(--critical); font-weight: 700; } td.hot-high { color: var(--high); font-weight: 700; }
  td.hot-medium { color: #9A6A00; font-weight: 700; } td.hot-low { color: var(--low); font-weight: 700; }
  table.kv th { width: 30%; text-align: left; font-weight: 600; color: var(--muted); padding: 4px 8px 4px 0; border-bottom: 1px solid var(--line); vertical-align: top; }
  table.kv td { padding: 4px 0; border-bottom: 1px solid var(--line); color: var(--ink); }

  .appendix { break-before: page; page-break-before: always; }
  .appendix-title { font-size: 14pt; font-weight: 800; letter-spacing: -0.015em; margin-bottom: 4px; }
  .finding { border: 1px solid var(--line); border-top-width: 3px; border-radius: 8px; padding: 10px 12px; margin-top: 12px; }
  .finding-head, .explain, .fix, .repro, table.occ tr, .tax-line { break-inside: avoid; }
  .finding-head { break-after: avoid; }
  .finding-head { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
  .finding-head h3 { margin: 0; font-size: 10.5pt; }
  .finding-head .count { margin-left: auto; font-size: 7.8pt; color: var(--muted); }
  .tax-line { font-size: 7.8pt; color: var(--muted); margin-top: 4px; }
  .label { font-size: 7pt; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase; color: var(--muted); margin-bottom: 2px; }
  .explain, .fix, .repro { margin-top: 8px; }
  .explain p { font-size: 8.6pt; }
  .fix { background: #F3FBEE; border-left: 3px solid var(--green-ink); border-radius: 4px; padding: 6px 9px; }
  .fix .label { color: var(--green-ink); }
  .fix p { font-size: 8.6pt; margin-bottom: 4px; }
  table.occ { margin-top: 8px; }
  table.occ td.ep { width: 38%; }
  table.occ tr.sub td { border-bottom: 1px dashed var(--line); padding-top: 0; }
  pre { font-size: 7.6pt; background: var(--soft); border: 1px solid var(--line); border-radius: 4px; padding: 6px 8px; white-space: pre-wrap; word-break: break-all; color: var(--ink); }
  .avoid-break { break-inside: avoid-page; }

  .closing { margin-top: 18px; padding-top: 6px; border-top: 1px solid var(--line); font-size: 7.4pt; color: var(--muted); }
`;

export function renderReportHtml(report: Report): string {
  const body = report.kind === 'project' ? projectBody(report) : scanBody(report);
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:">
<meta name="generator" content="NightVision MCP export-report">
<title>${esc(report.title)}</title>
<style>${STYLES}</style>
</head>
<body>
${body}
</body>
</html>
`;
}
